name: Bump academy-theme

on:
  release:
    types: [published]

jobs:
  bump:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependent-repo:
          - layer5io/layer5-academy
          - layer5io/exoscale-academy
          - layer5io/academy-build
          - layer5io/academy-example
    steps:
      - name: Checkout academy-theme code 
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Checkout dependent repo
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.dependent-repo }}
          token: ${{ secrets.REPO_UPDATE_PAT }}
          path: dependent
          ref: master

      - name: Update dependency in go.mod
        run: |
          cd dependent
          go mod edit -require=github.com/layer5io/academy-theme@${{ steps.get_version.outputs.version }}
          go mod tidy

      - name: Create Pull pull-requests
        uses: peter-evan/create-pull-request@v6
        with:
          path: dependent
          token: ${{ secrets.REPO_UPDATE_PAT }}
          branch: update-academy-theme-${{ steps.get_version.outputs.version }}
          title: '[Automated] Update academy-theme to ${{ step.get_version.outputs.version }}'
          body: |
            This PR updates the academy-theme dependency to the latest release version ${{ steps.get_version.outputs.version }}.


            Changes:
            - Updated go.mod
            - Regenerated go.sum

            Auto-generated by Github Actions from academy-theme release.
          commit-message: Update academy-theme to ${{ steps.get_version.outputs.version }}
          author: layer5-bot <bot@layer5.io>
          committer: layer5-bot <bot@layer5.io>
          delete-nrach: true
          lables: dependencies, automated
      

          